### ISSUE TITLE
Error when using the wstool

### ISSUE THREAD

**Issue by exodaniel** [ethz-asl/segmatch#16]
```
$ wstool update
[GTSAM] Updating /home/daniel/Documents/catkin_ws/src/GTSAM
[GTSAM] Done.
[Schweizer-Messer] Updating /home/daniel/Documents/catkin_ws/src/Schweizer-Messer
[Schweizer-Messer] Done.
[catkin_simple] Updating /home/daniel/Documents/catkin_ws/src/catkin_simple
[catkin_simple] Done.
[curves] Updating /home/daniel/Documents/catkin_ws/src/curves
Username for 'https://github.com': exodaniel
Password for 'https://exodaniel@github.com': 
WARNING [vcstools] Command failed: 'git checkout feature/discreteSE3Curve'
 run at: '/home/daniel/Documents/catkin_ws/src/curves'
 errcode: 1:
error: pathspec 'feature/discreteSE3Curve' did not match any file(s) known to git.
```

@rdube do you also see this error?

**Comment by rdube** [comment]
@exodaniel git pull? It seems like you are not using the latest dependencies.rosinstall script. You should be cloning mincurves and not curves.

**Comment by exodaniel** [comment]
I git cloned segmatch, and git checkout the autoencoder branch. Has the dependencies script changed since the branch's origin?

**Comment by rdube** [comment]
Try removing the curves folder in your catkin_ws

**Comment by rdube** [comment]
Otherwise you would have to clean the dependencies used by wstool. That most likely comes from the older scripts we were using.

**Comment by rdube** [comment]
You can do `wstool info` to see the entries and `wstool rm` to delete wrong one. Does that help?

**Comment by exodaniel** [comment]
Okay, previous dependencies were still present, your method works for removing them. Closing.
