### ISSUE TITLE
mincurves failed during installation

### ISSUE THREAD

**Issue by jayden118** [ethz-asl/segmatch#26]
Hi developers,

I am trying to install segmatch, but the installation is terminated during mincurves make.The error shown in terminal as below:

make[2]: *** [CmakeFiles/mincurves.dir/src/DiscreteSE3Curve.cpp.o] Error 1
make[1]: *** [CmakeFiles/mincurves.dir/all] Error 2
make: *** [all] Error 2

May I know how to solve this issue? 

Thank you in advance.

**Comment by gawela** [comment]
Hi @jayden118,

can you give the full error log?

Thanks!

**Comment by jayden118** [comment]
Hi @gawela 

Please find the error log as below:

[ 33%] [32mBuilding CXX object CMakeFiles/mincurves.dir/src/DiscreteSE3Curve.cpp.o
In file included from /home/jayden/catkin_ws/devel/include/gtsam/base/Manifold.h:23:0,
                 from /home/jayden/catkin_ws/src/minkindr_gtsam/minkindr_gtsam/include/kindr/minimal/quat-transformation-gtsam.h:28,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Config.hpp:11,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/DiscreteSE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/src/DiscreteSE3Curve.cpp:7:
/home/jayden/catkin_ws/devel/include/gtsam/base/Testable.h: In instantiation of ‘gtsam::IsTestable<T>::~IsTestable() [with T = kindr::minimal::QuatTransformationTemplate<double>]’:
/usr/include/boost/concept/detail/general.hpp:38:28:   required from ‘static void boost::concepts::requirement<boost::concepts::failed************ Model::************>::failed() [with Model = gtsam::IsTestable<kindr::minimal::QuatTransformationTemplate<double> >]’
/home/jayden/catkin_ws/devel/include/gtsam/base/FastSet.h:48:3:   required from ‘class gtsam::ExpressionFactor<kindr::minimal::QuatTransformationTemplate<double> >’
/home/jayden/catkin_ws/src/mincurves/mincurves/src/DiscreteSE3Curve.cpp:278:43:   required from here
/home/jayden/catkin_ws/devel/include/gtsam/base/Testable.h:65:25: error: no matching function for call to ‘gtsam::traits<kindr::minimal::QuatTransformationTemplate<double> >::Print(kindr::minimal::QuatTransformationTemplate<double>&)’
       traits<T>::Print(t);
                         ^
/home/jayden/catkin_ws/devel/include/gtsam/base/Testable.h:65:25: note: candidate is:
In file included from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Config.hpp:11:0,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/DiscreteSE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/src/DiscreteSE3Curve.cpp:7:
/home/jayden/catkin_ws/src/minkindr_gtsam/minkindr_gtsam/include/kindr/minimal/quat-transformation-gtsam.h:48:15: note: static void gtsam::traits<kindr::minimal::QuatTransformationTemplate<double> >::Print(const QuatTransformation&, const string&)
   static void Print(const kindr::minimal::QuatTransformation& T,
               ^
/home/jayden/catkin_ws/src/minkindr_gtsam/minkindr_gtsam/include/kindr/minimal/quat-transformation-gtsam.h:48:15: note:   candidate expects 2 arguments, 1 provided
In file included from /home/jayden/catkin_ws/devel/include/gtsam/base/Manifold.h:23:0,
                 from /home/jayden/catkin_ws/src/minkindr_gtsam/minkindr_gtsam/include/kindr/minimal/quat-transformation-gtsam.h:28,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Config.hpp:11,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/DiscreteSE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/src/DiscreteSE3Curve.cpp:7:
/home/jayden/catkin_ws/devel/include/gtsam/base/Testable.h:70:33: error: no matching function for call to ‘gtsam::traits<kindr::minimal::QuatTransformationTemplate<double> >::Equals(kindr::minimal::QuatTransformationTemplate<double>&, kindr::minimal::QuatTransformationTemplate<double>&)’
       r2 = traits<T>::Equals(t,t);
                                 ^
/home/jayden/catkin_ws/devel/include/gtsam/base/Testable.h:70:33: note: candidate is:
In file included from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Config.hpp:11:0,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/SE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/include/mincurves/DiscreteSE3Curve.hpp:10,
                 from /home/jayden/catkin_ws/src/mincurves/mincurves/src/DiscreteSE3Curve.cpp:7:
/home/jayden/catkin_ws/src/minkindr_gtsam/minkindr_gtsam/include/kindr/minimal/quat-transformation-gtsam.h:55:15: note: static bool gtsam::traits<kindr::minimal::QuatTransformationTemplate<double> >::Equals(const QuatTransformation&, const QuatTransformation&, double)
   static bool Equals(const kindr::minimal::QuatTransformation& T1,
               ^
/home/jayden/catkin_ws/src/minkindr_gtsam/minkindr_gtsam/include/kindr/minimal/quat-transformation-gtsam.h:55:15: note:   candidate expects 3 arguments, 2 provided
make[2]: *** [CMakeFiles/mincurves.dir/src/DiscreteSE3Curve.cpp.o] Error 1
make[1]: *** [CMakeFiles/mincurves.dir/all] Error 2
make: *** [all] Error 2

Thank you.

**Comment by rdube** [comment]
@jayden118 thanks for getting in touch! Can you please tell us on which commit you are for the GTSAM and minkindr_gtsam packages by running git log in these repositories?

**Comment by jayden118** [comment]
Hi @rdube 

I am sorry I could not understand your question. Can you please elaborate more on what I should do to provide information that you need?

Thank you.

**Comment by rdube** [comment]
Open a terminal and run:
`$ roscd minkindr_gtsam`

That will bring you inside this package. Then run:
 `$ git log`

And copy the first few lines here.

**Comment by jayden118** [comment]
Hi @rdube 

The log information as below:

commit a949b061622ede93958107e98f3c694b1bc5c445
Merge: cb250ec b363b0d
Author: rdube <renaud.dube@mavt.ethz.ch>
Date:   Tue Jun 28 18:02:50 2016 +0200

    Merge pull request #1 from ethz-asl/feature/import_from_minkindr
    
    Ported additions from minkindr that got lost in the package splitting.

commit b363b0ddc95b530271e0833a115b72961e7faa62
Author: Renaud Dube <renaud.dube@mavt.ethz.ch>
Date:   Tue Jun 28 15:46:47 2016 +0200

    addressed Hannes' comments

commit a5014878e9e9135532c2891c64bee3f79a80fadb
Author: gawela <abel.gawel@mavt.ethz.ch>
Date:   Mon Jun 13 16:22:28 2016 +0200

    Added pthread.

commit 2860bd277d819a02b97f74c1eab2913b7eb874c7

**Comment by rdube** [comment]
That is correct and can you please do the same in the GTSAM folder which is at the same level of the minkindr_gtsam one?

**Comment by jayden118** [comment]
Hi @rdube 

This is GTSAM log

commit 4e01dee06ba18aa3eb2a4b81549336d1f829a4c2
Merge: c9f95e7 5e538f9
Author: Kevin Egger <eggerk@users.noreply.github.com>
Date:   Tue Feb 14 13:54:23 2017 +0100

    Merge pull request #19 from ethz-asl/feature/update-gtsam
    
    Updated gtsam_catkin

commit 5e538f97741f660912678b0fb9002f3fd599ab7d
Author: Kevin Egger <eggerk@ethz.ch>
Date:   Tue Feb 14 12:35:29 2017 +0100

    Updated gtsam_catkin

commit c9f95e76bba7126ede3f98a967b1ba43e1372c22
Merge: 3498bd8 57bab00
Author: Simon Lynen <simon.lynen@mavt.ethz.ch>
Date:   Thu Jul 2 22:29:37 2015 +0200

    Merge pull request #16 from ethz-asl/fix/forward_make
    
    Forward make args

Thank you.

**Comment by rdube** [comment]
Ok we fixed our GTSAM version to an older commit. Did you use this file to pull every dependencies as instructed in the readme: https://github.com/ethz-asl/segmatch/blob/master/dependencies.rosinstall

You can now fix this by doing in the same GTSAM folder:

`$ git checkout b66dda2fe5ed2cf9e801119e481530e4cf13a94e`

And try to rebuild mincurves. That should solve your issue.

**Comment by jayden118** [comment]
This error is shown when I execute the git checkout 

fatal: reference is not a tree: b66dda2fe5ed2cf9e801119e481530e4cf13a94e

May I know how to fix this?

Thank you.

**Comment by jayden118** [comment]
Hi,

I followed all the instructions and recompile the codes again but still giving me the same error. 

It would be appreciated if you can give me some clue.

Thank you.

**Comment by gawela** [comment]
Hi @jayden118,

Sorry for letting you wait. I was able to reproduce your problem. There has been a recent update on one of the dependent packages which went unnoticed. Please do the following, we'll fix the rosinstall accordingly:

`roscd gtsam_catkin`

`git checkout c9f95e76bba7126ede3f98a967b1ba43e1372c22`

and then try to rebuild.

**Comment by rdube** [comment]
@jayden118 thanks for pointing us this issue which should be fixed with  #27. Please let us know whether it works now.

**Comment by jayden118** [comment]
Hi @rdube @gawela 

I have built the codes successfully. Thank you very much for your help.
