### ISSUE TITLE
Loop closure launch file needs update

### ISSUE THREAD

**Issue by hriapatil** [ethz-asl/segmatch#32]
I am unable to see any loop-closure using the KITTI dataset - 2011_09_30_drive_0027 when I launch  'kitti_loop_closure.launch' file. Any suggestions? Thanks!

**Comment by rdube** [comment]
Hi @hriapatil, the loop closure launch file is outdated and we are planning to release it very soon with instructions to run the loop closure demo. Otherwise what have you tried to get loop closures? Did you get the localization demo running? Thanks for trying it out!

**Comment by hriapatil** [comment]
Hi @rdube . I got the localization demo running with KITTI dataset. Look forward to testing the loop closure demo. Currently, I haven't tried any other loop closure techniques.

With regards to the localization module, I understand that the classifier '.xml' file is provided for the KITTI dataset. I was wondering how to create such a classifier file for other datasets?

**Comment by rdube** [comment]
HI @hriapatil we have now put online the instructions for running the loop-closure demonstration on the KITTI dataset which you can find here: https://github.com/ethz-asl/segmatch/wiki/Demonstrations#closing-loops-in-the-kitti-dataset. Thanks for letting us know if you try it out and run into any issue!

You are right, the classifier is provided with the `random_forest_eigen_25trees.xml` file. As for training a new random forest classifier, you would have to generate training data and use the OpenCV method `CvRTrees::train` which is described [here](http://docs.opencv.org/2.4/modules/ml/doc/random_trees.html). However, when experimenting with a different dataset, I would recommend first trying a simple k-NN retrieval which can potentially yield similar performances without the extra work of training a model. Please feel free to contact me directly if you have any question regarding your application-specific issues (see readme for contact info).

**Comment by YAMMAY** [comment]
Hi, I just run : roslaunch laser_mapper kitti_loop_closure.launch   , based on https://github.com/ethz-asl/segmatch/wiki/Demonstrations#closing-loops-in-the-kitti-dataset  .But can't see any cloud but path and segmentation at the rviz .
![screenshot from 2017-05-11 14 08 37](https://cloud.githubusercontent.com/assets/11918161/25935058/b554aede-3653-11e7-976b-17292a6d58b9.png)

**Comment by rdube** [comment]
@YAMMAY are you using the .rviz file mentioned in the wiki demonstration page? You should subscribe to /segmatch/source_representation and /segmatch/target_representation
