### ISSUE TITLE
setting up a proper catkin workspace

### ISSUE THREAD

**Issue by saimanoj18** [ethz-asl/segmatch#40]
Hi,

First of all, its a great work and congratulations on that!

Now, I followed the installation instructions on the github and got it to work. Specifically, 

1. I already have a ubuntu 14.04 with ROS Indigo and tried to install the source code in catkin_ws/src/ but was having some issues producing compiling erros, hence
2. I created a new folder and catkin_ws_segmatch and I followed the instruction on github and later i could get both localization and loop closure to work. 
3. Once I close the terminal and open a new terminal and try to replicate the steps then, it produces an error saying 

**ERROR: cannot launch node of type [laser_mapper/laser_mapper_node]: can't locate node [laser_mapper_node] in package [laser_mapper]**

I tried adding adding the line shown below in .bashrc file but it didnt help.
_export ROS_PACKAGE_PATH=/home/iirav/catkin_ws_segmatch/src:/home/iirav/catkin_ws/src:/opt/ros/indigo/share:/opt/ros/indigo/stacks_

Could you help in solving this issue ?

**Comment by lorenwel** [comment]
Have you tried sourcing your new workspace before running segmatch?
`source ~/catkin_ws_segmatch/devel/setup.bash`

However, this is not really a segmatch issue but rather a general catkin question on how to work with multiple workspaces. 
If my suggestion doesn't fix your problem consider asking this issue in a more appropriate place.

**Comment by saimanoj18** [comment]
That worked perfectly!
Thanks.
