### ISSUE TITLE
"https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by hriapatil** [ethz-asl/segmatch#41]
Hi, I tried compiling the packages and ran into the following error -
```
CMake Error at gflags_src-stamp/download-gflags_src.cmake:27 (message):
error: downloading 'https://github.com/gflags/gflags/archive/v2.1.2.zip'
failed

status_code: 1
status_string: "Unsupported protocol"
log: Protocol "https" not supported or disabled in libcurl

Closing connection -1
```

Any help is appreciated. Thanks!

**Comment by rdube** [comment]
Hi @hriapatil you might have an outdated version of curl. Can you please run: `$ curl --version`

Also this might be useful: https://askubuntu.com/questions/821186/protocol-https-not-supported-or-disabled-in-libcurl/821993

**Comment by hriapatil** [comment]
Hi @rdube , please find below the output of `$ curl --version` : 
```
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

**Comment by HannesSommer** [comment]
This is probably not related to curl itself but to `libcurl`. More specifically to which version `cmake` is dynamically linked to. The following should shed some light on this question:
`ldd $(which cmake) | grep curl`

This should yield the effectively linked `.so` file (=: `YOUR_SO_FILE`).
After that you would still need to figure out what the library you found supports or even better how to upgrade it. 
On dpkg based systems (Debian, Ubuntu, ..) you can do the first with :
`dpkg -S <YOUR_SO_FILE>`

**Comment by hriapatil** [comment]
I do not get any output from `ldd $(which cmake) | grep curl`

**Comment by HannesSommer** [comment]
Interesting! But we are getting closer. How did you get your `cmake`? Could it be that you compiled it from source? Of which distribution is your Linux? Could you maybe post the output of 
* `which cmake`
* `ldd $(which cmake)`
* `dpkg -S bin/cmake` (in case your Linux is `dpkg` based)
* `uname -a`
* `lsb_release -a`

**Comment by rdube** [comment]
Thank you very much @HannesSommer for your generous support!

**Comment by hriapatil** [comment]
Thank you @HannesSommer and @rdube  for your advice! I managed to solve the issue by reinstalling the libraries and ROS.

**Comment by rdube** [comment]
Good to hear that! Thank you for sharing your solution.

**Comment by HannesSommer** [comment]
Which were "the libraries" that you reinstalled? ROS should be irrelevant for this issue but reinstalling it might trigger some relevant library upgrade.

**Comment by hriapatil** [comment]
I actually reformatted my system. I believe there were many missing/corrupted links to various libraries.

**Comment by HannesSommer** [comment]
Ah, I see. Thanks for sharing.
