### ISSUE TITLE
Missing use_odom_factors parameter in parameter files

### ISSUE THREAD

**Issue by vkee** [ethz-asl/segmatch#44]
I think the use_odom_factors parameters is not set anywhere, if I am not mistaken? I don't see it in kitti_loop_closure.yaml or kitti_localization.yaml.

**Comment by vkee** [comment]
Is this normally not set / set to false so odometry factors are not created for some stability reasons? laser mapper seems to occasionally crash and have to respawn.

**Comment by rdube** [comment]
@vkee good catch! This parameter should be set to true for the current demonstration. Would you like to open a quick PR by adding this parameter? As mentioned before this parameter was added to experiment with LiDAR only odometry for our newest SegMatch version which will be uploaded later this year.

**Comment by vkee** [comment]
@rdube done.

**Comment by rdube** [comment]
@vkee great thank you!
