### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Varun1407** [ethz-asl/segmatch#53]
Hi all,

I am trying to use segmatch method with visual slam method for optimizing loop closure method. 
But i am obtaining the following error during catkin_make.

src/laser_slam_worker.cpp:72:17: error: ‘class pcl::VoxelGrid<pcl::PointXYZ>’ has no member named ‘setMinimumPointsNumberPerVoxel’
   voxel_filter_.setMinimumPointsNumberPerVoxel(params_.minimum_point_number_per_voxel);
                 ^

Kindly suggest solutions. 

regards,
varun

**Comment by rdube** [comment]
Hi @Varun1407 that sounds interesting! Did you follow the instructions in the readme for compiling segmatch?

**Comment by rdube** [comment]
@Varun1407 given the other issue that you opened, I would assume that this is now fixed. Can we close this?
