### ISSUE TITLE
Is segmatch deterministic?

### ISSUE THREAD

**Issue by Tacoma** [ethz-asl/segmatch#55]
Hi all,
I have tried the loop closure demonstration and also some own datasets and noticed that different runs with exactly same parameters return different outcomes. I have made small changes to the code so I cannot determine if I introduced the non-deterministic behaviour.
Did you also notice non-deterministic behaviour in your experiments and have an idea where it comes from?

**Comment by vkee** [comment]
Yes, I have gotten that before. I think it is because SegMatch is multi-threaded.

**Comment by Tacoma** [comment]
Thanks @vkee, that was also my guess besides the random forest and the ROS message system.
Good to know that I didn't break its :)
