### ISSUE TITLE
Performing ground segmentation

### ISSUE THREAD

**Issue by pclucas14** [ethz-asl/segmatch#56]
Hi, 

I need to perform semantic segmentation on LiDAR point clouds. After looking at your demo, it seems you have successfully solved this problem. Could you perhaps point me to the code that performs the point cloud segmentation? Or, if by any chance you already have a LiDAR dataset where each point is labelled that would be awesome :)

Thanks in advance, 
Lucas

**Comment by rdube** [comment]
Hi @pclucas14, for these demonstrations we simply filter the input point cloud based on the sensor height. This is done in the input filters parametrized [here](https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/input_filters_outdoor.yaml#L8).

If this does not work in your application I would encourage you to look at [this](https://github.com/lorenwel/linefit_ground_segmentation) ground removal implementation developed by Lorenz Wellhausen @lorenwel.

I hope that helps!

**Comment by pclucas14** [comment]
Hi @rdube , 

Thanks for getting back to me. I'm actually trying to classifiy every point in the LiDAR scan (e.g. as car, tree, road, truck, ..) and not just (road / not road). You have a nice [image](https://github.com/ethz-asl/segmatch/wiki/images/segment_examples.png) in your wiki that seems to be able to do that. Is there code for this ground/vehicle/obstacle segmentation ?

**Comment by rdube** [comment]
With the current implementation, we are not assigning semantics to the segments. You could however use the segmentation part if this is the kind of segments that you are looking for. You could also take a look at the descriptors we are using. They might be interesting for the classification task.

**Comment by rdube** [comment]
@pclucas14 I will close this issue and feel free to re-open if it is still relevant!

**Comment by Sajjadmanal** [comment]
@pclucas14 Were you able to classify trees, cars, walls, etc? It will be much useful if you could share.
