### ISSUE TITLE
 laser_mapper.launch file not working 

### ISSUE THREAD

**Issue by ytgcljj** [ethz-asl/segmatch#59]
Hi all,

i am trying to  roslaunch laser_mapper.launch 
[laser_mapper-2] restarting process
process[laser_mapper-2]: started with pid [4741]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1108 15:35:18.640985  4741 segmatch.cpp:18] Do not forget to initialize SegMatch.
F1108 15:35:18.656913  4741 common.hpp:133] Check failed: loop_closure_noise_model.size() == kNoiseModelDimension (0 vs. 6) 
*** Check failure stack trace: ***
[laser_mapper-2] process has died [pid 4741, exit code -6, cmd /home/t450-14/aaa_ws/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/t450-14/.ros/log/5de4a75c-c457-11e7-87e0-1002b5e35684/laser_mapper-2.log].
log file: /home/t450-14/.ros/log/5de4a75c-c457-11e7-87e0-1002b5e35684/laser_mapper-2*.log

Thanks in advance.

**Comment by rdube** [comment]
Hi @ytgcljj It looks like the parameters (in the .yaml file) did not load properly. I would recommend that you have a look at the [demonstrations page](https://github.com/ethz-asl/segmatch/wiki/Demonstrations#localization-in-the-kitti-dataset)

What you can try to run is: `$ roslaunch laser_mapper kitti_localization.launch`

**Comment by ytgcljj** [comment]
thank you rdube  
I'm downloading the BAG file and trying again ，The following mistakes are reported

I1108 17:54:34.732282 16121 common.hpp:135] Loading cloud: /home/t450-14/aaa_ws/src/segmatch/laser_mapper/demonstration_files/kitti/drive27_target_map.pcd.
[player-4] process has died [pid 16122, exit code 1, cmd /opt/ros/indigo/lib/rosbag/play -r 1 -s 333 --clock --pause /home/t450-14/aaa_ws/src/segmatch/laser_mapper/demonstration_files/kitti/2011_10_03_drive_27.bag __name:=player __log:=/home/t450-14/.ros/log/d298adc4-c46a-11e7-86c4-507b9de082e4/player-4.log].
log file: /home/t450-14/.ros/log/d298adc4-c46a-11e7-86c4-507b9de082e4/player-4*.log

**Comment by ytgcljj** [comment]
thank you rdube
i can run roslaunch laser_mapper kitti_localization.launch but do not run  roslaunch laser_mapper.launch 

t450-14@t45014-ThinkPad-T450:~/aaa_ws/src/segmatch/laser_mapper/launch$ roslaunch laser_mapper.launch 
... logging to /home/t450-14/.ros/log/6ae0c770-c4ec-11e7-9247-507b9de082e4/roslaunch-t45014-ThinkPad-T450-18624.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://t45014-ThinkPad-T450:43402/

SUMMARY
========

PARAMETERS
 * /laser_mapper/icp_configuration_file: /home/t450-14/aaa...
 * /laser_mapper/icp_input_filters_file: /home/t450-14/aaa...
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    laser_mapper (laser_mapper/laser_mapper_node)

auto-starting new master
process[master]: started with pid [18636]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6ae0c770-c4ec-11e7-9247-507b9de082e4
process[rosout-1]: started with pid [18649]
started core service [/rosout]
process[laser_mapper-2]: started with pid [18653]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1109 09:22:15.089155 18653 segmatch.cpp:18] Do not forget to initialize SegMatch.
F1109 09:22:15.105399 18653 common.hpp:133] Check failed: loop_closure_noise_model.size() == kNoiseModelDimension (0 vs. 6) 
*** Check failure stack trace: ***
[laser_mapper-2] process has died [pid 18653, exit code -6, cmd /home/t450-14/aaa_ws/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/t450-14/.ros/log/6ae0c770-c4ec-11e7-9247-507b9de082e4/laser_mapper-2.log].
log file: /home/t450-14/.ros/log/6ae0c770-c4ec-11e7-9247-507b9de082e4/laser_mapper-2*.log
[laser_mapper-2] restarting process
process[laser_mapper-2]: started with pid [18706]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1109 09:22:15.460724 18706 segmatch.cpp:18] Do not forget to initialize SegMatch.
F1109 09:22:15.480417 18706 common.hpp:133] Check failed: loop_closure_noise_model.size() == kNoiseModelDimension (0 vs. 6) 
*** Check failure stack trace: ***
[laser_mapper-2] process has died [pid 18706, exit code -6, cmd /home/t450-14/aaa_ws/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/t450-14/.ros/log/6ae0c770-c4ec-11e7-9247-507b9de082e4/laser_mapper-2.log].
log file: /home/t450-14/.ros/log/6ae0c770-c4ec-11e7-9247-507b9de082e4/laser_mapper-2*.log

**Comment by rdube** [comment]
@ytgcljj you cannot solely launch laser_mapper.launch as information will be missing. Take a look at what is inside kitti_localization.launch to see what needs to be launched & loaded. I will look at the other issue mentioned above.

**Comment by rdube** [comment]
@ytgcljj did you get the demo running with `$ roslaunch laser_mapper kitti_localization.launch` ?

**Comment by ytgcljj** [comment]
@rdube i run the demo with $ roslaunch laser_mapper kitti_localization.launch  is OK

**Comment by ytgcljj** [comment]
i run roslaunch laser_mapper.launch。Do you need to turn on the lidar?

**Comment by rdube** [comment]
@ytgcljj it is not sufficient to launch only laser_mapper.launch. You need to launch either kitti_localization.launch or kitti_loop_closure.launch which will play the bag, load parameters, launch the mapper and more. See where the mapper is launched here: 

https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/kitti_localization.launch#L35

If this is not clear I would recommend looking into the ros tutorials, particularly the following one, section 2.2:

http://wiki.ros.org/ROS/Tutorials/UsingRqtconsoleRoslaunch

**Comment by rdube** [comment]
@ytgcljj I will assume that the use of kitti_loop_closure.launch is clear by now and will close this issue.
