### ISSUE TITLE
Error when parsing the random forest xml file

### ISSUE THREAD

**Issue by wfcola** [ethz-asl/segmatch#62]
Following the instruction in the document, I typed the cmd "roslaunch laser_mapper kitti_localization.launch " after catkin build the project, the error below showing up. How can i fix this problem?

process[laser_mapper-3]: started with pid [7956]
 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093        [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       WARNING: Logging before InitGoogleLogging() is written to STDERR
I1127 11:14:43.709179  7956 segmatch.cpp:18] Do not forget to initialize SegMatch.
 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       I1127 11:14:43.792932  7956 laser_track.cpp:16] Loading ICP configurations from: /home/wfcola/catkin_ws/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
I1127 11:14:43.793896  7956 laser_track.cpp:26] Loading ICP input filters from: /home/wfcola/catkin_ws/src/segmatch/laser_mapper/launch/kitti/input_filters_outdoor.yaml
I1127 11:14:43.794366  7956 laser_track.cpp:48] Creating ICP noise model with cauchy.
I1127 11:14:43.794412  7956 incremental_estimator.cpp:31] Creating loop closure noise model with cauchy.
I1127 11:14:43.794433  7956 incremental_estimator.cpp:54] Loading ICP configurations from: /home/wfcola/catkin_ws/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       OpenCV Error: Parsing error (/home/wfcola/catkin_ws/src/segmatch/laser_mapper/demonstration_files/kitti/random_forest_eigen_25trees.xml(95678): Too long string or a last string w/o newline) in icvXMLSkipSpaces, file /home/wfcola/Downloads/opencv-2.4.13.4/modules/core/src/persistence.cpp, line 1838
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/wfcola/Downloads/opencv-2.4.13.4/modules/core/src/persistence.cpp:1838: error: (-212) /home/wfcola/catkin_ws/src/segmatch/laser_mapper/demonstration_files/kitti/random_forest_eigen_25trees.xml(95678): Too long string or a last string w/o newline in function icvXMLSkipSpaces

 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093        [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       [laser_mapper-3] process has died [pid 7956, exit code -6, cmd /home/wfcola/catkin_ws/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/wfcola/.ros/log/ca83a174-d320-11e7-a349-00215cc3552d/laser_mapper-3.log].
log file: /home/wfcola/.ros/log/ca83a174-d320-11e7-a349-00215cc3552d/laser_mapper-3*.log

**Comment by rdube** [comment]
That might be an issue with the opencv version. Can you please run one of the following and copy paste the output? 
`$ dpkg -l | grep libopencv` or
`pkg-config --modversion opencv`

**Comment by wfcola** [comment]
Here is the output:


ii  libopencv-calib3d-dev:amd64                  2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-calib3d
ii  libopencv-calib3d2.4v5:amd64                 2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Camera Calibration library
ii  libopencv-contrib-dev:amd64                  2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-contrib
ii  libopencv-contrib2.4v5:amd64                 2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision contrib library
ii  libopencv-core-dev:amd64                     2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-core
ii  libopencv-core2.4v5:amd64                    2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision core library
ii  libopencv-dev                                2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for opencv
ii  libopencv-features2d-dev:amd64               2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-features2d
ii  libopencv-features2d2.4v5:amd64              2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Feature Detection and Descriptor Extraction library
ii  libopencv-flann-dev:amd64                    2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-flann
ii  libopencv-flann2.4v5:amd64                   2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Clustering and Search in Multi-Dimensional spaces library
ii  libopencv-gpu-dev:amd64                      2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-gpu2.4v5
ii  libopencv-gpu2.4v5:amd64                     2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision GPU library
ii  libopencv-highgui-dev:amd64                  2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-highgui
ii  libopencv-highgui2.4v5:amd64                 2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision High-level GUI and Media I/O library
ii  libopencv-imgproc-dev:amd64                  2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-imgproc
ii  libopencv-imgproc2.4v5:amd64                 2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Image Processing library
ii  libopencv-legacy-dev:amd64                   2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-legacy
ii  libopencv-legacy2.4v5:amd64                  2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision legacy library
ii  libopencv-ml-dev:amd64                       2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-ml
ii  libopencv-ml2.4v5:amd64                      2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Machine Learning library
ii  libopencv-objdetect-dev:amd64                2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-objdetect
ii  libopencv-objdetect2.4v5:amd64               2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Object Detection library
ii  libopencv-ocl-dev:amd64                      2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-ocl2.4v5
ii  libopencv-ocl2.4v5:amd64                     2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision OpenCL support library
ii  libopencv-photo-dev:amd64                    2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-photo2.4v5
ii  libopencv-photo2.4v5:amd64                   2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision computational photography library
ii  libopencv-stitching-dev:amd64                2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-stitching2.4v5
ii  libopencv-stitching2.4v5:amd64               2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision image stitching library
ii  libopencv-superres-dev:amd64                 2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-superres2.4v5
ii  libopencv-superres2.4v5:amd64                2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Super Resolution library
ii  libopencv-ts-dev:amd64                       2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-ts2.4v5
ii  libopencv-ts2.4v5:amd64                      2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision ts library
ii  libopencv-video-dev:amd64                    2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-video
ii  libopencv-video2.4v5:amd64                   2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision Video analysis library
ii  libopencv-videostab-dev:amd64                2.4.9.1+dfsg-1.5ubuntu1                               amd64        development files for libopencv-videostab2.4v5
ii  libopencv-videostab2.4v5:amd64               2.4.9.1+dfsg-1.5ubuntu1                               amd64        computer vision video stabilization library
ii  libopencv2.4-java                            2.4.9.1+dfsg-1.5ubuntu1                               all          Java bindings for the computer vision library
ii  libopencv2.4-jni                             2.4.9.1+dfsg-1.5ubuntu1                               amd64        Java jni library for the computer vision library

**Comment by wfcola** [comment]
Here is the output of cmd "pkg-config --modversion opencv"

2.4.13.4

**Comment by rdube** [comment]
Could it be that you have two different version of opencv on your system? I have no issue with version 2.4.8. Also regarding "Too long string or a last string w/o newline" have you tried maybe adding an empty last string to the xml file?

**Comment by wfcola** [comment]
I uninstall the opencv2.4.13.4.
Then both the cmd "pkg-config --modversion opencv" and " pkg-config --modversion opencv" give the same vision of 2.4.9.
I changed nothing of the source files except i regedit the CMakeList.txt of minkindr_gtsam to add the INCLUDE_DIRECTORIES path of GTSAM. And GTSAM file could not be catkin build from source so i build the GTSAM independently. 
After that re-catkin build the project and the output is following.


[laser_mapper-3] restarting process
process[laser_mapper-3]: started with pid [32342]
 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       WARNING: Logging before InitGoogleLogging() is written to STDERR
I1129 10:26:20.336477 32342 segmatch.cpp:18] Do not forget to initialize SegMatch.
 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       I1129 10:26:20.405735 32342 laser_track.cpp:16] Loading ICP configurations from: /home/wfcola/catkin_ws/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
I1129 10:26:20.406713 32342 laser_track.cpp:26] Loading ICP input filters from: /home/wfcola/catkin_ws/src/segmatch/laser_mapper/launch/kitti/input_filters_outdoor.yaml
I1129 10:26:20.407116 32342 laser_track.cpp:48] Creating ICP noise model with cauchy.
I1129 10:26:20.407158 32342 incremental_estimator.cpp:31] Creating loop closure noise model with cauchy.
I1129 10:26:20.407173 32342 incremental_estimator.cpp:54] Loading ICP configurations from: /home/wfcola/catkin_ws/src/segmatch/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       OpenCV Error: Parsing error (/home/wfcola/catkin_ws/src/segmatch/laser_mapper/demonstration_files/kitti/random_forest_eigen_25trees.xml(95678): Too long string or a last string w/o newline) in icvXMLSkipSpaces, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp, line 1838
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/core/src/persistence.cpp:1838: error: (-212) /home/wfcola/catkin_ws/src/segmatch/laser_mapper/demonstration_files/kitti/random_forest_eigen_25trees.xml(95678): Too long string or a last string w/o newline in function icvXMLSkipSpaces

 [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093        [PAUSED ]  Bag Time: 1317639667.992462   Duration: 0.000000 / 137.842093       [laser_mapper-3] process has died [pid 32342, exit code -6, cmd /home/wfcola/catkin_ws/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/wfcola/.ros/log/a9fc0904-d4ac-11e7-a349-00215cc3552d/laser_mapper-3.log].
log file: /home/wfcola/.ros/log/a9fc0904-d4ac-11e7-a349-00215cc3552d/laser_mapper-3*.log

**Comment by rdube** [comment]
Have you tried adding a blank line at the end of the file?

**Comment by wfcola** [comment]
Yes, but nothing changed.

**Comment by rdube** [comment]
Ok it might simply be an issue that the model was saved with opencv 2.4.8 and can't be reloaded in 2.4.9.. Any chance that you could easily install 2.4.8? 

In case you want to experiment with the pipeline without the random forest, you could simply put the following parameter to false: https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/kitti_localization.yaml#L88

Then reduce the number of nearest neighbors: https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/kitti_localization.yaml#L86

And finally remove the code responsible for loading the random forest. You should then get very similar performances. I wish I would have more time to invest in debugging that issue but we are currently working on a much more powerful descriptor which will deprecate the use of the random forest. This new version will be open sourced in the next few months and we will not be supporting the random forest anymore. Therefore you can choose whether you would like to further investigate that opencv issue or experiment with simple k-nn retrieval and wait for the new descriptor. I hope that helps!

**Comment by wfcola** [comment]
Dear rdube,
    Lots of thanks.
   It's my bad, that the data downloaded from kitti has some problem and i re-download from website and all the program works well. The function is supported by opencv2.4.13 well.

**Comment by rdube** [comment]
Happy to hear that! So it wasn't an opencv issue after all? That error message is quite misleading then!

**Comment by tiandaji** [comment]
Hello, rdube!

I managed to compile the segmap source code by following the instruction from the wiki demo. However, while launching the kitti_localization.launch file, I could see the pcd map loaded, but nothing more.  I thought for a long time, and conclude three questions that you may have some ideas on: 

1. where can I download the random_forest_eigen_25trees.xml file? There is no mention of it at all on the wiki demo page, after some search on the internet, I found nothing;
2. I do not know whether or not it is because of the lack of this xml file, the laser_mapper process dies as soon as I start to play the bagfile;
3. "Failed to find match for field 'intensity" issue, from what I find on the internet, It is caused by pcl calling the intensity field 'intensity' and ros calling it 'intensities'(https://answers.ros.org/question/173396/losing-intensity-data-when-converting-between-sensor_msgspointcloud2-and-pclpointcloudt/). Have you ever encountered this problem? As I can see from the drive27_target_map.pcd file, there is no intensity information at all. Maybe that is the problem?

At last, I copy the output in the terminal before and after I played the rosbag file for you to see the problem more clearly. When I began to play the bagfile, the laser_mapper process died, and restarted again and again, that's why I had to shutdown the whole process.
Hope you have some hints for my issues, and thanks a lot in advance.

**output in the terminal before I start to play the bagfile**
```
roslaunch laser_mapper kitti_localization.launch 
... logging to /home/daji/.ros/log/95a9a6f0-51c5-11e8-a856-4ce676fb89f7/roslaunch-daji-desktop-12621.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://daji-desktop:39347/

SUMMARY
========

PARAMETERS
 * /LaserMapper/LaserSlamWorker/assembled_cloud_sub_topic: /velodyne_points
 * /LaserMapper/LaserSlamWorker/create_filtered_map: True
 * /LaserMapper/LaserSlamWorker/distance_to_consider_fixed: 80
 * /LaserMapper/LaserSlamWorker/distant_map_pub_topic: distant_map
 * /LaserMapper/LaserSlamWorker/full_map_pub_topic: full_map
 * /LaserMapper/LaserSlamWorker/local_map_pub_topic: local_map
 * /LaserMapper/LaserSlamWorker/map_publication_rate_hz: 3
 * /LaserMapper/LaserSlamWorker/minimum_distance_to_add_pose: 1
 * /LaserMapper/LaserSlamWorker/minimum_point_number_per_voxel: 1
 * /LaserMapper/LaserSlamWorker/odom_frame: world
 * /LaserMapper/LaserSlamWorker/odometry_trajectory_pub_topic: odometry_trajectory
 * /LaserMapper/LaserSlamWorker/publish_distant_map: False
 * /LaserMapper/LaserSlamWorker/publish_full_map: False
 * /LaserMapper/LaserSlamWorker/publish_local_map: True
 * /LaserMapper/LaserSlamWorker/sensor_frame: velodyne
 * /LaserMapper/LaserSlamWorker/separate_distant_map: True
 * /LaserMapper/LaserSlamWorker/trajectory_pub_topic: trajectory
 * /LaserMapper/LaserSlamWorker/use_odometry_information: True
 * /LaserMapper/LaserSlamWorker/voxel_size_m: 0.1
 * /LaserMapper/OnlineEstimator/LaserTrack/add_m_estimator_on_icp: True
 * /LaserMapper/OnlineEstimator/LaserTrack/add_m_estimator_on_odom: False
 * /LaserMapper/OnlineEstimator/LaserTrack/force_priors: False
 * /LaserMapper/OnlineEstimator/LaserTrack/icp_noise_model: [0.05, 0.05, 0.05...
 * /LaserMapper/OnlineEstimator/LaserTrack/nscan_in_sub_map: 20
 * /LaserMapper/OnlineEstimator/LaserTrack/nscan_to_match: 3
 * /LaserMapper/OnlineEstimator/LaserTrack/odometry_noise_model: [0.5, 0.5, 0.5, 0...
 * /LaserMapper/OnlineEstimator/LaserTrack/save_icp_results: False
 * /LaserMapper/OnlineEstimator/LaserTrack/use_icp_factors: False
 * /LaserMapper/OnlineEstimator/LaserTrack/use_odom_factors: True
 * /LaserMapper/OnlineEstimator/add_m_estimator_on_loop_closures: True
 * /LaserMapper/OnlineEstimator/do_icp_step_on_loop_closures: True
 * /LaserMapper/OnlineEstimator/loop_closure_noise_model: [0.005, 0.005, 0....
 * /LaserMapper/OnlineEstimator/loop_closures_sub_maps_radius: 3
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/apply_hard_threshold_on_feature_distance: False
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/classifier_filename: /home/daji/my_ws/...
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/enable_two_stage_retrieval: True
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/feature_distance_threshold: 1
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/knn_feature_dim: 7
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/max_eigen_features_values: [2493.5, 186681.0...
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/n_nearest_neighbours: 200
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/normalize_eigen_for_hard_threshold: True
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/normalize_eigen_for_knn: False
 * /LaserMapper/SegMatchWorker/SegMatch/Classifier/threshold_to_accept_match: 0.7
 * /LaserMapper/SegMatchWorker/SegMatch/Descriptors/descriptor_types: ['EigenvalueBased']
 * /LaserMapper/SegMatchWorker/SegMatch/GeometricConsistency/min_cluster_size: 4
 * /LaserMapper/SegMatchWorker/SegMatch/GeometricConsistency/resolution: 0.4
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/ec_max_cluster_size: 15000
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/ec_min_cluster_size: 200
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/ec_tolerance: 0.2
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_curvature_threshold: 0.05
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_knn_for_growing: 30
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_knn_for_normals: 100
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_max_cluster_size: 50000
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_min_cluster_size: 100
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_radius_for_normals: 0.5
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/rg_smoothness_threshold_deg: 4.0
 * /LaserMapper/SegMatchWorker/SegMatch/Segmenters/segmenter_type: EuclideanSegmenter
 * /LaserMapper/SegMatchWorker/SegMatch/boundary_radius_m: 999.0
 * /LaserMapper/SegMatchWorker/SegMatch/centroid_distance_threshold_m: 2.0
 * /LaserMapper/SegMatchWorker/SegMatch/check_pose_lies_below_segments: False
 * /LaserMapper/SegMatchWorker/SegMatch/filter_boundary_segments: True
 * /LaserMapper/SegMatchWorker/SegMatch/filter_duplicate_segments: True
 * /LaserMapper/SegMatchWorker/SegMatch/min_time_between_segment_for_matches_s: 0
 * /LaserMapper/SegMatchWorker/SegMatch/segmentation_height_above_m: 999.0
 * /LaserMapper/SegMatchWorker/SegMatch/segmentation_height_below_m: 999.0
 * /LaserMapper/SegMatchWorker/SegMatch/segmentation_radius_m: 60.0
 * /LaserMapper/SegMatchWorker/align_target_map_on_first_loop_closure: False
 * /LaserMapper/SegMatchWorker/close_loops: False
 * /LaserMapper/SegMatchWorker/distance_between_segmentations_m: 1.0
 * /LaserMapper/SegMatchWorker/distance_to_lower_target_cloud_for_viz_m: 15.0
 * /LaserMapper/SegMatchWorker/export_segments_and_matches: False
 * /LaserMapper/SegMatchWorker/line_scale_loop_closures: 5.0
 * /LaserMapper/SegMatchWorker/line_scale_matches: 0.5
 * /LaserMapper/SegMatchWorker/localize: True
 * /LaserMapper/SegMatchWorker/publish_predicted_segment_matches: False
 * /LaserMapper/SegMatchWorker/ratio_of_points_to_keep_when_publishing: 1.0
 * /LaserMapper/SegMatchWorker/target_cloud_filename: /home/daji/my_ws/...
 * /LaserMapper/bag_file: /home/daji/my_ws/...
 * /LaserMapper/clear_local_map_after_loop_closure: False
 * /LaserMapper/publish_world_to_odom: True
 * /LaserMapper/tf_publication_rate_hz: 10
 * /LaserMapper/world_frame: map
 * /laser_mapper/icp_configuration_file: /home/daji/my_ws/...
 * /laser_mapper/icp_input_filters_file: /home/daji/my_ws/...
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /
    laser_mapper (laser_mapper/laser_mapper_node)
    player (rosbag/play)
    visualizer (rviz/rviz)

auto-starting new master
process[master]: started with pid [12631]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 95a9a6f0-51c5-11e8-a856-4ce676fb89f7
process[rosout-1]: started with pid [12644]
started core service [/rosout]
process[visualizer-2]: started with pid [12670]
process[laser_mapper-3]: started with pid [12671]
process[player-4]: started with pid [12672]
[ INFO] [1525676970.319287505]: Opening /home/daji/my_ws/src/segmap/laser_mapper/demonstration_files/kitti/2011_10_03_drive_27.bag

Waiting 0.2 seconds after advertising topics...[ INFO] [1525676970.460686104]: rviz version 1.12.15
[ INFO] [1525676970.460748525]: compiled against Qt version 5.5.1
[ INFO] [1525676970.460767310]: compiled against OGRE version 1.9.0 (Ghadamon)
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0507 15:09:30.596972 12671 segmatch.cpp:18] Do not forget to initialize SegMatch.
 done.

Hit space to toggle paused, or 's' to step.
I0507 15:09:30.665827 12671 laser_track.cpp:16] Loading ICP configurations from: /home/daji/my_ws/src/segmap/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
I0507 15:09:30.667053 12671 laser_track.cpp:26] Loading ICP input filters from: /home/daji/my_ws/src/segmap/laser_mapper/launch/kitti/input_filters_outdoor.yaml
I0507 15:09:30.667587 12671 laser_track.cpp:48] Creating ICP noise model with cauchy.
I0507 15:09:30.667631 12671 incremental_estimator.cpp:31] Creating loop closure noise model with cauchy.
I0507 15:09:30.667651 12671 incremental_estimator.cpp:54] Loading ICP configurations from: /home/daji/my_ws/src/segmap/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
inverted_max_eigen_double_ 
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
inverted_max_eigen_float_ 
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
[ INFO] [1525676970.707679293, 1317639667.992462073]: Stereo is NOT SUPPORTED
[ INFO] [1525676970.707876242, 1317639667.992462073]: OpenGl version: 3 (GLSL 1.3).
[ INFO] [1525676970.707874982]: Loading target cloud.
I0507 15:09:30.708043 12671 common.hpp:135] Loading cloud: /home/daji/my_ws/src/segmap/laser_mapper/demonstration_files/kitti/drive27_target_map.pcd.
Failed to find match for field 'intensity'.uration: 0.000000 / 137.842093               
I0507 15:09:55.643805 12671 euclidean_segmenter.cpp:28] Starting euclidean segmentation.
I0507 15:10:17.414736 12671 euclidean_segmenter.cpp:42] Segmentation complete. Took 21771.4ms and found 1026 clusters.
I0507 15:10:17.424316 12671 segmatch.cpp:149] Removing too near segments from source map.
I0507 15:10:17.424499 12671 segmatch.cpp:844] segment_ids.size() 1026
I0507 15:10:17.428266 12671 segmatch.cpp:919] Removed 19 duplicate segments in 4.378 ms.
I0507 15:10:17.479403 12671 descriptors.cpp:61] Decriptor 0 took 51.563 ms.
```


**output in the terminal after I start to play the bagfile**
```
[ WARN] [1525677041.533029591, 1317639668.205416432]: [SegMapper] Timeout while waiting between world and velodyne.
I0507 15:10:41.654582 12965 euclidean_segmenter.cpp:28] Starting euclidean segmentation.
I0507 15:10:41.732771 12965 euclidean_segmenter.cpp:42] Segmentation complete. Took 78.672ms and found 3 clusters.
I0507 15:10:41.733091 12965 segmatch.cpp:683] Removed 0 boundary segments.
I0507 15:10:41.733120 12965 segmatch.cpp:78] Removing too near segments from source map.
I0507 15:10:41.733150 12965 segmatch.cpp:844] segment_ids.size() 3
I0507 15:10:41.733310 12965 segmatch.cpp:919] Removed 0 duplicate segments in 0.667 ms.
I0507 15:10:41.733623 12965 segmatch_worker.cpp:110] Processing the source cloud took 80.128 ms.
I0507 15:10:41.733724 12965 opencv_random_forest.cpp:171] Two stage retrieval with RF and 1007 segments in the target cloud.
OpenCV Error: Bad argument (This function works for binary classification problems only...) in predict_prob, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/ml/src/rtrees.cpp, line 721
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/ml/src/rtrees.cpp:721: error: (-5) This function works for binary classification problems only... in function predict_prob

[laser_mapper-3] process has died [pid 12671, exit code -6, cmd /home/daji/my_ws/devel/lib/laser_mapper/laser_mapper_node __name:=laser_mapper __log:=/home/daji/.ros/log/95a9a6f0-51c5-11e8-a856-4ce676fb89f7/laser_mapper-3.log].
log file: /home/daji/.ros/log/95a9a6f0-51c5-11e8-a856-4ce676fb89f7/laser_mapper-3*.log
[laser_mapper-3] restarting process
process[laser_mapper-3]: started with pid [12992]
WARNING: Logging before InitGoogleLogging() is written to STDERR37.842093               
I0507 15:10:42.316813 12992 segmatch.cpp:18] Do not forget to initialize SegMatch.
I0507 15:10:42.495662 12992 laser_track.cpp:16] Loading ICP configurations from: /home/daji/my_ws/src/segmap/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
I0507 15:10:42.498134 12992 laser_track.cpp:26] Loading ICP input filters from: /home/daji/my_ws/src/segmap/laser_mapper/launch/kitti/input_filters_outdoor.yaml
I0507 15:10:42.498818 12992 laser_track.cpp:48] Creating ICP noise model with cauchy.
I0507 15:10:42.498927 12992 incremental_estimator.cpp:31] Creating loop closure noise model with cauchy.
I0507 15:10:42.498973 12992 incremental_estimator.cpp:54] Loading ICP configurations from: /home/daji/my_ws/src/segmap/laser_mapper/launch/kitti/icp_dynamic_outdoor.yaml
inverted_max_eigen_double_ 39668.819857   Duration: 0.827394 / 137.842093               
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
inverted_max_eigen_float_ 
0.000401043 5.35673e-06 5.30817e-06     3.02663 5.30819e-06    0.917515      1.0013
[ INFO] [1525677042.569015382, 1317639668.819856545]: Loading target cloud.
I0507 15:10:42.569324 12992 common.hpp:135] Loading cloud: /home/daji/my_ws/src/segmap/laser_mapper/demonstration_files/kitti/drive27_target_map.pcd.
Failed to find match for field 'intensity'.uration: 0.827394 / 137.842093               
I0507 15:11:30.470094 12992 euclidean_segmenter.cpp:28] Starting euclidean segmentation.
[visualizer-2] process has finished cleanlyuration: 0.827394 / 137.842093               
log file: /home/daji/.ros/log/95a9a6f0-51c5-11e8-a856-4ce676fb89f7/visualizer-2*.log
^C[player-4] killing on exit9668.819857   Duration: 0.827394 / 137.842093               
[laser_mapper-3] killing on exit
 [PAUSED ]  Bag Time: 1317639668.819857   Duration: 0.827394 / 137.842093               
^C^C
^CI0507 15:12:00.804800 12992 euclidean_segmenter.cpp:42] Segmentation complete. Took 30335.2ms and found 1026 clusters.
I0507 15:12:00.812664 12992 segmatch.cpp:149] Removing too near segments from source map.
I0507 15:12:00.812860 12992 segmatch.cpp:844] segment_ids.size() 1026
I0507 15:12:00.815944 12992 segmatch.cpp:919] Removed 19 duplicate segments in 3.718 ms.
I0507 15:12:00.856446 12992 descriptors.cpp:61] Decriptor 0 took 40.929 ms.
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by rdube** [comment]
@tiandaji did you pull the latest master? Did you modify the .yaml parameters i.e. this one: https://github.com/ethz-asl/segmap/blob/master/segmapper/launch/kitti/kitti_localization.yaml#L86 ?
