### ISSUE TITLE
This function works for binary classification problems only... in function predict_prob

### ISSUE THREAD

**Issue by szm88** [ethz-asl/segmatch#63]
I have the problen when I use the model trained by my dataset : "opencv-2.4.8+dfsg1/modules/ml/src/rtrees.cpp:721: error: (-5) This function works for binary classification problems only... in function predict_prob" anyone can give some suggestions?

**Comment by rdube** [comment]
How did you train your classifier? Which parameter values did you set?

**Comment by szm88** [comment]
Even i use the model of segmatch to save the map,it alse has the problem. i didn't change the parameter of segmatch.

**Comment by rdube** [comment]
I understand that you tried the classifier file provided here: http://robotics.ethz.ch/segmatch/ and that you still experience the same issue. Is that correct? Can you please make sure that the path is set correctly? Where did you save the file?

**Comment by szm88** [comment]
@rdube  thanks very much.I update the code,and recompile it.Now its ok.

**Comment by rdube** [comment]
@szm88 great! I will close this issue feel free to re-open if it is relevant!
