### ISSUE TITLE
Build error in ubuntu 16.04

### ISSUE THREAD

**Issue by YuxiHuang1** [ethz-asl/segmatch#64]
Hi, I'm trying to run segmatch on ubuntu 16.04,I notice that I should run `catkin config --merge-devel` before `catkin build -DCMAKE_BUILD_TYPE=Release laser_mapper`，and I did so, But I still get error "Error: The current devel space layout, `linked`,is incompatible with the configured layout, `merged`." . How to fix this error？ Thanks a lot !

**Comment by YuxiHuang1** [comment]
I think I have found where the problem is. I delete the .catkin_tools and devel,build folders，Then run `catkin config --merge-devel` and `catkin build -DCMAKE_BUILD_TYPE=Release laser_mapper` it works, maybe because when I build this package first time I did not notice the note and generate wrong .catkin_tools folder. Anyway, it works, but I found this package depends on OpenCV2, but default OpenCV version of kinetic is OpenCV3, that's the problem I need to fix next or do you have any suggestions to fix this?

**Comment by rdube** [comment]
Hi @YuxiHuang1 yes that might very well be the issue. I have moved the note up in the installation instructions in order to avoid this problem in the future. 

As for the opencv issue, what error are you getting exactly? Have you installed libopencv-dev?

**Comment by YuxiHuang1** [comment]
Hi,@rdube,thanks for your reply, I have download opencv 2.4.9 from[https://github.com/opencv/opencv/releases/tag/2.4.9](url), and intall it from the source，and change find_package(OpenCV 2 REQUIRED) to find_package(OpenCV 2.4.9 REQUIRED) in segmatch CMakeLists.txt, then I can compile the package successfully.

**Comment by rdube** [comment]
Great! Happy to see that you managed to compile segmatch! I'll hint to the present thread if someone has the same issue in the future. It would normally be preferable to open a PR to fix this issue but that will not be necessary here as we will update segmatch in the near future and remove the dependency to opencv. Can we close this issue? Thank you!
