### ISSUE TITLE
Almost impossible to get segment_matches

### ISSUE THREAD

**Issue by YuxiHuang1** [ethz-asl/segmatch#67]
Hi, I run the loop_closure.launch with my data, so I can get a map.But when I run the localization, I find that it's almost impossible to get segment_matches. I find that predicted_matches is enough，but few of them can pass GeometricConsistencyGrouping,because the clustered_corrs size is 0. I think maybe the model of classifier is not appropriate for my data. The data is recorded in the campus. 
1.What do you think is the main cause of this？
2.I find that there is a train function in opencv_random_forest.cpp，may I ask how do you use this function? Need special labeling tools to do this?
Thanks a lot!

**Comment by rdube** [comment]
Can you give more information about the environment? Maybe post a few images and screenshots of the segments you are obtaining? How many segments do you in average get in your local map? As a start, you could consider using only knn retrieval (no classifier) see explanations in #62. You could also consider using the region growing segmenter (see #50). 

You could try to increase the resolution (https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/kitti_loop_closure.yaml#L98) and / or the minimum cluster size (https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/kitti_loop_closure.yaml#L99) until you start getting false positives. Then move back to more conservative values and see if you can still get true positives.

Finally that page might also help: [https://github.com/ethz-asl/segmatch/wiki/Parametrizing-SegMatch](https://github.com/ethz-asl/segmatch/wiki/Parametrizing-SegMatch)

**Comment by rdube** [comment]
Also did you manage to run the demonstrations?
